name: flake8 / pytest

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "${{ matrix.python-version }}"
    - name: Apt install dependencies
      run: |
        sudo apt update ; sudo apt-get -y install 
    - name: Install Python tools
      run: |
        python -m pip install --upgrade pip
        pip install poetry autopep8 pytest
    - name: Lint
      run: |
        autopep8 src/ tests/
    - name: Pytest
      run: |
        poetry install
        poetry run pytest

